<a href="https://colab.research.google.com/github/kriogenia/my_learnings/blob/machine_learning/pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)

2.4.0+cu121


# Tensors


## Creating Tensors

### Manual

#### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

#### Vector

In [5]:
vector = torch.tensor([2, 3])
vector

tensor([2, 3])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

#### Matrix

In [8]:
MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

#### Tensor

In [12]:
TENSOR = torch.tensor([
    [[3, 6, 9], [2, 4, 5]],
    [[2, 0, 2], [1, 6, 7]],
    [[1, 1, 1], [5, 5, 5]],
    [[5, 2, 9], [4, 7, 9]]
    ])
TENSOR

tensor([[[3, 6, 9],
         [2, 4, 5]],

        [[2, 0, 2],
         [1, 6, 7]],

        [[1, 1, 1],
         [5, 5, 5]],

        [[5, 2, 9],
         [4, 7, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([4, 2, 3])

### Random tensors

The way neural networks learn is starting with tensors of random number that are then adjusted to better represent the data.

In [15]:
RANDOM_TENSOR = torch.rand(3, 4)
RANDOM_TENSOR

tensor([[0.3214, 0.0444, 0.7068, 0.1720],
        [0.8637, 0.6935, 0.4594, 0.5610],
        [0.9679, 0.2538, 0.0404, 0.1763]])

In [16]:
height = 1280
width = 720
color_channels = 3
RANDOM_IMAGE_TENSOR = torch.rand(
    size = ( height, width, color_channels )
)

RANDOM_IMAGE_TENSOR.shape, RANDOM_IMAGE_TENSOR.ndim

(torch.Size([1280, 720, 3]), 3)

### Zeroes and ones

In [17]:
ZEROES = torch.zeros(3, 4)
ZEROES

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ONES = torch.ones(4, 2)
ONES

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [19]:
ONES.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [20]:
a_range = torch.arange(
    start = 0,
    end = 100,
    step = 5)
a_range

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [21]:
zeroes_like = torch.zeros_like(a_range)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note**: tensor datatypes are one of the three big problems one could get into with PyTorch and deep learning, being wrong shape and wrong device the other two

In [22]:
float_16_tensor = torch.tensor(
    [1.0, 2.0],
    dtype = torch.float16,  # data type of the tense
    device = None,          # device where the tensor is on, for example "cpu" or "cuda"
    requires_grad = False   # whether or not to track gradience
)
float_16_tensor

tensor([1., 2.], dtype=torch.float16)

In [23]:
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor

tensor([1., 2.])

In [24]:
float_16_tensor * float_32_tensor

tensor([1., 4.])

In [25]:
int_32_tensor = torch.tensor([3, 2], dtype=torch.int32)
float_32_tensor * int_32_tensor

tensor([3., 4.])

### Getting information from tensors

1. Tensor not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensor not on on the right device - `tensor.device`

In [27]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape:    {some_tensor.shape}")
print(f"Device:   {some_tensor.device}")

tensor([[0.9575, 0.2600, 0.8541, 0.5065],
        [0.7014, 0.7969, 0.4314, 0.6759],
        [0.6774, 0.5184, 0.2227, 0.1172]])
Datatype: torch.float32
Shape:    torch.Size([3, 4])
Device:   cpu


## Tensor operations

### Arithmetic operations

- Addition
- Substraction
- Element-wise multiplication
- Matrix multiplication
- Division
- Transpose

In [51]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [52]:
tensor * 10

tensor([10, 20, 30])

In [53]:
tensor - 10

tensor([-9, -8, -7])

In [54]:
# PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [55]:
# Scalar product
print(tensor, "*", tensor, "=", tensor * tensor)

# Dot product
print(tensor, "·", tensor, "=", tensor @ tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
tensor([1, 2, 3]) · tensor([1, 2, 3]) = tensor(14)


In [56]:
torch.rand(2, 3) @ torch.rand(3, 4) # inner dimensions must match

tensor([[1.1254, 0.8290, 0.3802, 0.2827],
        [0.9652, 0.6593, 0.2817, 0.2343]])

In [63]:
tensor_3x2 = torch.rand(3, 2)
print(tensor_3x2)
tensor_3x2.T

tensor([[0.3369, 0.8119],
        [0.8905, 0.3810],
        [0.6589, 0.3046]])


tensor([[0.3369, 0.8905, 0.6589],
        [0.8119, 0.3810, 0.3046]])

In [65]:
tensor_3x2 @ tensor_3x2.T

tensor([[0.7726, 0.6093, 0.4693],
        [0.6093, 0.9381, 0.7028],
        [0.4693, 0.7028, 0.5270]])

### Aggregations

In [68]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [71]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [74]:
torch.mean(x.type(torch.float32)) # must be float or complex types, integers are not valid as their mean could be decimal

tensor(45.)

In [75]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [77]:
torch.median(x), x.median()

(tensor(40), tensor(40))

In [81]:
argmin = x.argmin() # position in the tensor of the minimum value
x[argmin]

tensor(0)

In [80]:
torch.argmax(x), x.argmax() # position in the tensor of the maximum value

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing

- Reshaping, changes the shape of a tensor
- View, returns a view of a tensor of certain shape but pointing to the memory of the original tensor
- Stacking, combines multiple tensors
  - On top of each other: `vstack`
  - Side by side: `hstack`
- Squeezing, remove all single dimensions from a tensor.
- Unsqueezing, adds a single dimension to a tensor.
- `Permute`, returns a view of the input with dimensions swapped in a certain way.

In [91]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [95]:
x_reshaped = x.reshape(3, 2, 2) # must be a number compatible with the number of elements to move 3x2x2 = 1x12
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.],
          [ 3.,  4.]],
 
         [[ 5.,  6.],
          [ 7.,  8.]],
 
         [[ 9., 10.],
          [11., 12.]]]),
 torch.Size([3, 2, 2]))

In [97]:
z = x.view(3, 4)
z

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [98]:
# changing z would change x
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]))

In [118]:
y = torch.tensor([1, 2, 3])
print(torch.stack([y, y, y]))
print(torch.stack([y, y, y], dim=1))
print(torch.stack([y, y, y], dim=-1))
print(torch.stack([y, y, y], dim=-2))
print(torch.vstack([y, y, y]))
print(torch.hstack([y, y, y]))

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])


In [119]:
x = torch.zeros(2, 1, 2, 3, 1)
print(x.shape)
print(torch.squeeze(x).shape)

torch.Size([2, 1, 2, 3, 1])
torch.Size([2, 2, 3])


In [125]:
torch.unsqueeze(x, dim=3).shape

torch.Size([2, 1, 2, 1, 3, 1])

In [128]:
torch.permute(x, (2, 3, 0, 1, 4)).shape

torch.Size([2, 3, 2, 1, 1])