<a href="https://colab.research.google.com/github/kriogenia/my_learnings/blob/machine_learning/pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.__version__)

2.3.0+cu121


# Tensors


## Creating Tensors

### Manual

#### Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

#### Vector

In [ ]:
vector = torch.tensor([2, 3])
vector

tensor([2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

#### Matrix

In [ ]:
MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

#### Tensor

In [ ]:
TENSOR = torch.tensor([
    [[3, 6, 9], [2, 4, 5]],
    [[2, 0, 2], [1, 6, 7]],
    [[1, 1, 1], [5, 5, 5]],
    [[5, 2, 9], [4, 7, 9]]
    ])
TENSOR

tensor([[[3, 6, 9],
         [2, 4, 5]],

        [[2, 0, 2],
         [1, 6, 7]],

        [[1, 1, 1],
         [5, 5, 5]],

        [[5, 2, 9],
         [4, 7, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([4, 2, 3])

### Random tensors

The way neural networks learn is starting with tensors of random number that are then adjusted to better represent the data.

In [5]:
RANDOM_TENSOR = torch.rand(3, 4)
RANDOM_TENSOR

tensor([[0.5078, 0.9373, 0.0491, 0.8311],
        [0.2599, 0.2117, 0.7527, 0.9257],
        [0.8060, 0.7927, 0.1973, 0.0598]])

In [7]:
height = 1280
width = 720
color_channels = 3
RANDOM_IMAGE_TENSOR = torch.rand(
    size = ( height, width, color_channels )
)

RANDOM_IMAGE_TENSOR.shape, RANDOM_IMAGE_TENSOR.ndim

(torch.Size([1280, 720, 3]), 3)

### Zeroes and ones

In [23]:
ZEROES = torch.zeros(3, 4)
ZEROES

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ONES = torch.ones(4, 2)
ONES

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [22]:
ONES.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [19]:
range = torch.arange(
    start = 0,
    end = 100,
    step = 5)
range

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [24]:
zeroes_like = torch.zeros_like(range)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])