<a href="https://colab.research.google.com/github/kriogenia/my_learnings/blob/machine_learning/pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

print(torch.__version__)

2.2.1+cu121


# Tensors


## Creating Tensors

### Scalar

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

### Vector

In [9]:
vector = torch.tensor([2, 3])
vector

tensor([2, 3])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

### Matrix

In [12]:
matrix = torch.tensor([[7, 8], [8, 10]])
matrix

tensor([[ 7,  8],
        [ 8, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
matrix[0]

tensor([7, 8])

### Tensor

In [30]:
tensor = torch.tensor([
    [[3, 6, 9], [2, 4, 5]],
    [[2, 0, 2], [1, 6, 7]],
    [[1, 1, 1], [5, 5, 5]],
    [[5, 2, 9], [4, 7, 9]]
    ])
tensor

tensor([[[3, 6, 9],
         [2, 4, 5]],

        [[2, 0, 2],
         [1, 6, 7]],

        [[1, 1, 1],
         [5, 5, 5]],

        [[5, 2, 9],
         [4, 7, 9]]])

In [31]:
tensor.ndim

3

In [32]:
tensor.shape

torch.Size([4, 2, 3])